-- Flyway 초기 마이그레이션: 기본 정보 테이블 생성
CREATE TABLE IF NOT EXISTS app_info (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(64) NOT NULL DEFAULT 'maru',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET = utf8mb4;

